#!/bin/bash

declare -A NICLIST

COUNT=$(cat /proc/net/dev | awk 'NR>2{print $1}' | sed 's/://' | wc -l)
i=1
j=3

for i in $COUNT;do
	NICLIST[$i]=$(cat /proc/net/dev | awk 'NR==$j{print $1}' | sed 's/://')
	let j=j+1
done

for i in $COUNT;do
	echo NICLIST[$i]
done

