#!/bin/bash
# ---------------------------------------------------------------------------
# dmap - Generate alias config for hardware

# Copyright 2016, Brett Kelly <bkelly@45drives.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

usage() { # Help
        cat << EOF
Usage:	dmap
		[-c] Specify Disk Controller
		[-m] Creates map but doesnt trigger udev rules
		[-s] Specify chassis size
		[-q] Quiet Mode
		[-r] Resets drive map
		[-h] Displays this message

EOF
        exit 0
}
gethba() {
	case $1 in
	R750|r750|r|r3740|R3740)
		read -p "r750 or r3740? " hpt
		case $hpt in
		r750)
			DISK_CONTROLLER=$R750
			;;
		r3740A)
			DISK_CONTROLLER=$R3740
			;;
		*)
			echo "Didnt catch that try again"
			exit 1
			;;
		esac
		;;
	LSI|lsi|l)
		read -p "9361,9305 or 9201? " lsi
		case $lsi in
		9361)
			DISK_CONTROLLER=$LSI_9361
			;;
		9305)
			DISK_CONTROLLER=$LSI_9305
			;;
		9201)
			DISK_CONTROLLER=$LSI_9201
			;;
		*)
			echo "Didnt catch that try again"
			exit 1
			;;
		esac
		;;
	Adaptec|adaptec|a)
		read -p "ASR81605Z or HBA1000?(a/h) " adap
		case $adap in
		a)
			DISK_CONTROLLER=$ASR
			;;
		h)
			DISK_CONTROLLER=$HBA1000
			;;
		*)
			echo "Didnt catch that try again"
			exit 1
			;;
		esac
		;;
	*)
		echo "Unsupported controller, try configurating manually"
		exit 0
		;;	
	esac
}
checkchassis(){
	if [ $1 -eq 30 ] || [ $1 -eq 45 ] || [ $1 -eq 60 ] || [ $1 -eq 15 ];then
		:
	elif [ $1 -eq 40 ];then	
		if [ "$DISK_CONTROLLER" == "$R750" ];then
			:
		else
			echo "Chassis: $1 is only supported for Controller: $R750"
			exit 0
		fi
	elif [ $1 -eq 15 ];then
		if [ "$DISK_CONTROLLER" == "$R750" ];then
			echo "Chassis: $1 is not supported for Controller: $R750"
			exit 0
		else
			:
		fi		
	else
		echo "$1 is not an available chassis size, (15,30,45,60 or 40(lite))"
		exit 0
	fi
}
checkroot(){
	SCRIPT_NAME=$(basename "$0")
	if [ "$EUID" -ne 0 ];then
		echo "You must have root privileges to run $SCRIPT_NAME"
		exit 0
	fi
}

R750="0750"
LSI_9201="2116"
LSI_9305="3224"I
LSI_9361="3316"
ASR="Adaptec"
HBA1000="Adaptec Series 8"
R3740="3740"
DISK_CONTROLLER=
CHASSIS=
QUIET=no
RESET_MAP=no
UDEV_TRIG=yes

while getopts 'c:ms:qrh' OPTION; do
	case ${OPTION} in
	c)
		DISK_CONTROLLER=${OPTARG}
		;;
	s)
		CHASSIS=${OPTARG}
		;;
	m)
		UDEV_TRIG=no
		;;
	q)
		QUIET=yes
		;;
	r)
		RESET_MAP=yes
		;;
	h)
		usage
		;;
	esac
done

checkroot

if [ $RESET_MAP == yes ];then
	rm -f /etc/zfs/vdev_id.conf
	udevadm trigger
	udevadm settle
	echo "Drive Aliasing reset"
	exit 0
fi
if [ -z $DISK_CONTROLLER ] || [ -z $CHASSIS ]; then
	read -p "Disk Controller? " DISK_CONTROLLER
	read -p "Chassis Size? " CHASSIS
fi

gethba $DISK_CONTROLLER
checkchassis $CHASSIS

if [ "$DISK_CONTROLLER" == "$R750" ];then
	/opt/gtools/bin/mapr750 $CHASSIS $DISK_CONTROLLER
elif [ "$DISK_CONTROLLER" == "$LSI_9201" ];then
	/opt/gtools/bin/mapSAS2116 $CHASSIS $DISK_CONTROLLER
elif [ "$DISK_CONTROLLER" == "$LSI_9305" ];then
	/opt/gtools/bin/mapSAS3224 $CHASSIS $DISK_CONTROLLER
elif [ "$DISK_CONTROLLER" == "$ASR" ];then
	/opt/gtools/bin/mapadaptec $CHASSIS $DISK_CONTROLLER
elif [ "$DISK_CONTROLLER" == "$RR3740" ];then
	/opt/gtools/bin/maprr3740 $CHASSIS $DISK_CONTROLLER
elif [ "$DISK_CONTROLLER" == "$HBA1000" ];then
	/opt/gtools/bin/mapadaptec $CHASSIS $DISK_CONTROLLERi
elif [ "$DISK_CONTROLLER" == "$LSI_9361" ];then
	/opt/gtools/bin/mapSAS3316 $CHASSIS $DISK_CONTROLLER
fi

if [ $UDEV_TRIG == "yes" ];then
	udevadm trigger
	udevadm settle
fi

if [ $QUIET == "yes" ];then
	:
else
	cat /etc/zfs/vdev_id.conf
fi

