#!/bin/bash
# ---------------------------------------------------------------------------
# tunepool -Given zpool name apply tunables 

# Copyright 2016, Brett Kelly <bkelly@45drives.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

checkroot(){
	SCRIPT_NAME=$(basename "$0")
	if [ "$EUID" -ne 0 ];then
		echo "You must have root privileges to run $SCRIPT_NAME"
		exit 0
	fi
}
checkroot
POOL_NAME=$1
QUIET=$2
WORKING_NODE=$(hostname -s)

zfs set atime=off $POOL_NAME
zfs set xattr=sa $POOL_NAME
zfs set exec=off $POOL_NAME
zfs set sync=disabled $POOL_NAME
zfs set compression=lz4 $POOL_NAME
zfs set acltype=posixacl $POOL_NAME
zfs set aclinherit=passthrough $POOL_NAME
if [ "$QUIET" == "yes" ];then
	:
else
	echo -e "Applied the Following Tunables on $WORKING_NODE:\n"
	zfs get atime $POOL_NAME | awk 'NR==2'
	zfs get xattr $POOL_NAME | awk 'NR==2'
	zfs get exec $POOL_NAME | awk 'NR==2'
	zfs get sync $POOL_NAME | awk 'NR==2'
	zfs get compression $POOL_NAME | awk 'NR==2'
	zfs get acltype $POOL_NAME | awk 'NR==2'
	zfs get aclinherit $POOL_NAME | awk 'NR==2"	
	echo
fi
