#!/bin/bash
usage() {
        cat << EOF
Usage: ./zpool [-h]
       ./zpool [-s Chassis CHASSIS] [-r RAID Level] [-l Layout]

  -s    specify CHASSIS of chassis (i.e 30, 45, 60)
  -r    specify RAID level (i.e. raidz1, raidz2, raidz3, mirror)
  -l	specify vdev layout (i.e max storage eff, max IO perf)
  -c	custom vdev layout flag
  -t 	tune dataset flag. If present will apply default tunes to zpool and all children datasets.
  -h    show this summary
EOF
        exit 0
}

pause(){ # Waits for user input to continue
read -p "Press Enter to continue" con
case $con in
*)
	;;
esac
}

while getopts 's:r:l:cth' OPTION; do
	case ${OPTION} in
	s)
		CHASSIS=${OPTARG}
		;;
	r)
		RAID_LEVEL=${OPTARG}
		;;
	l)
		LAYOUT=${OPTARG}
		;;
	c)
		CUSTOM_LAYOUT=yes
		;;
	t)
		TUNE_POOL=yes
		;;
	h)
		usage
		;;
	esac
done

if [ "$CUSTOM_LAYOUT" == "yes" ] && [ -z $LAYOUT ];then
	echo "customvdevs yo"
	echo "but sorry"
	echo "its not wired up yet tho"
	exit
	#custom_pool
fi
#pause
case $CHASSIS in
30)
	if [ "$LAYOUT" == IO ]; then
		echo -e "Creating Zpool...\nDisks: $CHASSIS\nRAID: $RAID_LEVEL\nLayout: $LAYOUT"
		zpool create zpool \
		$RAID_LEVEL 1-1 1-2 1-3 1-4 1-5 1-6 \
		$RAID_LEVEL 1-7 1-8 1-9 1-10 1-11 1-12 \
		$RAID_LEVEL 1-13 1-14 1-15 1-16 1-17 1-18 \
		$RAID_LEVEL 1-19 1-20 1-21 1-22 1-23 1-24 \
		$RAID_LEVEL 1-25 1-26 1-27 1-28 1-29 1-30 \
		-f
	elif [ "$LAYOUT" == storage ]; then
		echo -e "Creating Zpool...\nDisks: $CHASSIS\nRAID: $RAID_LEVEL\nLayout: $LAYOUT"
		zpool create zpool \
		$RAID_LEVEL 1-1 1-2 1-3 1-4 1-5 1-6 1-7 1-8 1-9 1-10 \
		$RAID_LEVEL 1-11 1-12 1-13 1-14 1-15 1-16 1-17 1-18 1-19 1-20 \
		$RAID_LEVEL 1-21 1-22 1-23 1-24 1-25 1-26 1-27 1-28 1-29 1-30 \
		-f
	fi
	;;
45)
	if [ "$LAYOUT" == IO ]; then
		echo -e "Creating Zpool...\nDisks: $CHASSIS\nRAID: $RAID_LEVEL\nLayout: $LAYOUT"
		zpool create zpool \
		$RAID_LEVEL 1-1 1-2 1-3 1-4 1-5 \
		$RAID_LEVEL 1-6 1-7 1-8 1-9 1-10 \
		$RAID_LEVEL 1-11 1-12 1-13 1-14 1-15 \
		$RAID_LEVEL 1-16 1-17 1-18 1-19 1-20 \
		$RAID_LEVEL 1-21 1-22 1-23 1-24 2-1 \
		$RAID_LEVEL 2-2 2-3 2-4 2-5 2-6 \
		$RAID_LEVEL 2-7 2-8 2-9 2-10 2-11 \
		$RAID_LEVEL 2-12 2-13 2-14 2-15 2-16 \
		$RAID_LEVEL 2-17 2-18 2-19 2-20 2-21 \
		-f
	elif [ "$LAYOUT" == storage ]; then
		echo -e "Creating Zpool...\nDisks: $CHASSIS\nRAID: $RAID_LEVEL\nLayout: $LAYOUT"
		zpool create zpool \
		$RAID_LEVEL 1-1 1-2 1-3 1-4 1-5 1-6 1-7 1-8 1-9 1-10 1-11 1-12 1-13 1-14 1-15 \
		$RAID_LEVEL 1-16 1-17 1-18 1-19 1-20 1-21 1-22 1-23 1-24 2-1 2-2 2-3 2-4 2-5 2-6 \
		$RAID_LEVEL  2-7 2-8 2-9 2-10 2-11 2-12 2-13 2-14 2-15 2-16 2-17 2-18 2-19 2-20 2-21 \
		-f
	fi
	;;
60)
	if [ "$LAYOUT" == IO ]; then
		echo -e "Creating Zpool...\nDisks: $CHASSIS\nRAID: $RAID_LEVEL\nLayout: $LAYOUT"
		zpool create zpool \
		$RAID_LEVEL 1-1 1-2 1-3 1-4 1-5 1-6 1-7 1-8 1-9 1-10 \
		$RAID_LEVEL 1-11 1-12 1-13 1-14 1-15 1-16 1-17 1-18 1-19 1-20 \
		$RAID_LEVEL 1-21 1-22 1-23 1-24 1-25 1-26 1-27 1-28 1-29 1-30 \
		$RAID_LEVEL 1-31 1-32 2-1 2-2 2-3 2-4 2-5 2-6 2-7 2-8 \
		$RAID_LEVEL 2-9 2-10 2-11 2-12 2-13 2-14 2-15 2-16 2-17 2-18 \
		$RAID_LEVEL 2-19 2-20 2-21 2-22 2-23 2-24 2-25 2-26 2-27 2-28 \
		-f
	elif [ "$LAYOUT" == storage ]; then
		echo -e "Creating Zpool...\nDisks: $CHASSIS\nRAID: $RAID_LEVEL\nLayout: $LAYOUT"
		zpool create zpool \
		$RAID_LEVEL 1-1 1-2 1-3 1-4 1-5 1-6 1-7 1-8 1-9 1-10 1-11 1-12 1-13 1-14 1-15 \
		$RAID_LEVEL 1-16 1-17 1-18 1-19 1-20 1-21 1-22 1-23 1-24 1-25 1-26 1-27 1-28 1-29 1-30 \
		$RAID_LEVEL 1-31 1-32 2-1 2-2 2-3 2-4 2-5 2-6 2-7 2-8 2-9 2-10 2-11 2-12 2-13 \
		$RAID_LEVEL 2-14 2-15 2-16 2-17 2-18 2-19 2-20 2-21 2-22 2-23 2-24 2-25 2-26 2-27 2-29 \
		-f
	fi
	;;
*)
	;;
esac

if [ "$TUNE_POOL" == "yes" ];then
	sh /setup/tuneDataset.sh
fi

