#!/bin/bash

usage() { # Help
        cat << EOF
Usage:	dmap
		[-c] Specify Disk Controller
		[-m] Creates map but doesnt trigger udev rules
		[-s] Specify chassis size
		[-q] Quiet Mode
		[-r] Resets drive map
		[-h] Displays this message

EOF
        exit 0
}
gethba() {
	case $1 in
	R750|r750|r)
		DISK_CONTROLLER=$R750
		;;
	LSI|lsi|l)
		DISK_CONTROLLER=$LSI_9201
		;;
	Adaptec|adaptec|a) 
		DISK_CONTROLLER=$ADAPTEC
		;;
	rr3740|rr)
		DISK_CONTROLLER=$RR3740
		;;
	*)
		echo "Unsupported controller, try configurating manually"
		exit 0
		;;	
	esac
}
checkchassis(){
	if [ $1 -eq 30 ] || [ $1 -eq 45 ] || [ $1 -eq 60 ];then
		:
	elif [ $1 -eq 40 ];then	
		if [ "$DISK_CONTROLLER" == "$R750" ];then
			:
		else
			echo "Chassis: $1 is only supported for Controller: $R750"
			exit 0
		fi		
	else
		echo "$1 is not an available chassis size, (30,45,60 or 40(lite))"
		exit 0
	fi
}
checkroot(){
	SCRIPT_NAME=$(basename "$0")
	if [ "$EUID" -ne 0 ];then
		echo "You must have root privileges to run $SCRIPT_NAME"
		exit 0
	fi
}

R750="0750"
LSI_9201="2116"
ADPATEC="Adaptec"
RR3740="3740"
DISK_CONTROLLER=
CHASSIS=
QUIET=no
RESET_MAP=no
UDEV_TRIG=yes

while getopts 'c:ms:qrh' OPTION; do
	case ${OPTION} in
	c)
		DISK_CONTROLLER=${OPTARG}
		;;
	s)
		CHASSIS=${OPTARG}
		;;
	m)
		UDEV_TRIG=no
		;;
	q)
		QUIET=yes
		;;
	r)
		RESET_MAP=yes
		;;
	h)
		usage
		;;
	esac
done

checkroot

if [ $RESET_MAP == yes ];then
	rm -f /etc/zfs/vdev_id.conf
	udevadm trigger
	udevadm settle
	echo "Drive Aliasing reset"
	exit 0
fi
if [ -z $DISK_CONTROLLER ] || [ -z $CHASSIS ]; then
	read -p "Disk Controller? " DISK_CONTROLLER
	read -p "Chassis Size? " CHASSIS
fi

gethba $DISK_CONTROLLER
checkchassis $CHASSIS

if [ "$DISK_CONTROLLER" == "$R750" ];then
	/opt/gtools/bin/mapr750 $CHASSIS $DISK_CONTROLLER
elif [ "$DISK_CONTROLLER" == "$LSI_9201" ];then
	/opt/gtools/bin/maplsi $CHASSIS $DISK_CONTROLLER
elif [ "$DISK_CONTROLLER" == "$ADAPTEC" ];then
	/opt/gtools/bin/mapASR81605Z $CHASSIS $DISK_CONTROLLER
elif [ "$DISK_CONTROLLER" == "$RR3740" ];then
	/opt/gtools/bin/maprr3740 $CHASSIS $DISK_CONTROLLER
fi

if [ $UDEV_TRIG == "yes" ];then
	udevadm trigger
	udevadm settle
fi

if [ $QUIET == "yes" ];then
	:
else
	cat /etc/zfs/vdev_id.conf
fi

