#!/bin/bash

usage() {
        cat << EOF
Usage:	./dmap	[ -c hba controller ] [ -s chassis size ]

EOF
        exit 0
}
usage() { # Help
        cat << EOF
Usage:	dmap
		[-c] Specify Disk Controller
		[-s] Specify chassis size
		[-q] Quiet Mode
		[-r] Resets drive map
		[-h] Displays this message

EOF
        exit 0
}
R750="0750"
LSI_9201="2116"
ADPATEC="Adaptec"
RR3740="3740"

gethba() {
	case $1 in
	R750|r750|r)
		DISK_CONTROLLER=$R750
		;;
	LSI|lsi|l)
		DISK_CONTROLLER=$LSI_9201
		;;
	Adaptec|adaptec|a) 
		DISK_CONTROLLER=$ADAPTEC
		;;
	rr3740|rr)
		DISK_CONTROLLER=$RR3740
		;;
	*)
		echo "Unsupported controller, try configurating manually"
		exit 0
		;;	
	esac
}
checkchassis(){
	if [ $1 -eq 30 ] || [ $1 -eq 45 ] || [ $1 -eq 60 ];then
		:
	else
		echo "$1 is not an available chassis size, (30,45, or 60)"
	fi
}

DISK_CONTROLLER=
CHASSIS=
QUIET=no
RESET_MAP=no

while getopts 'c:s:qrh' OPTION; do
	case ${OPTION} in
	c)
		DISK_CONTROLLER=${OPTARG}
		;;
	s)
		CHASSIS=${OPTARG}
		;;
	q)
		QUIET=yes
		;;
	r)
		RESET_MAP=yes
		;;
	h)
		usage
		;;
	esac
done

if [ $RESET_MAP == yes ];then
	rm -f /etc/zfs/vdev_id.conf
	udevadm trigger
	echo "Drive Aliasing reset"
	exit 0
fi
if [ -z $DISK_CONTROLLER ] || [ -z $CHASSIS ]; then
	read -p "Disk Controller? " DISK_CONTROLLER
	read -p "Chassis Size? " CHASSIS
fi

gethba $DISK_CONTROLLER
checkchassis $CHASSIS

if [ "$DISK_CONTROLLER" == "$R750" ];then
	mapr750 $CHASSIS $DISK_CONTROLLER
elif [ "$DISK_CONTROLLER" == "$LSI_9201" ];then
	maplsi $CHASSIS $DISK_CONTROLLER
elif [ "$DISK_CONTROLLER" == "$ADAPTEC" ];then
	mapadptc1000 $CHASSIS $DISK_CONTROLLER
elif [ "$DISK_CONTROLLER" == "$RR3740" ];then
	echo $RR3740
	maprr3740 $CHASSIS $DISK_CONTROLLER
fi
if [ $QUIET == "yes" ];then
	:
else
	cat /etc/zfs/vdev_id.conf
fi

