#!/bin/bash

CHASSIS=$1
DISK_CONTROLLER=$2

if [ -e /etc/zfs/vdev_id.conf ];then
        rm -f /etc/zfs/vdev_id.conf
fi

echo "# by-vdev" >> /etc/zfs/vdev_id.conf
echo "# name     fully qualified or base name of device link" >> /etc/zfs/vdev_id.conf
case $CHASSIS in
30)
	card1=$(lspci | grep $DISK_CONTROLLER | awk 'NR==1{print $1}')
	#Card 1
	slot=1
	while [ $slot -lt 31 ];do
       	echo "alias 1-$slot     /dev/disk/by-path/pci-0000:$card1-scsi-0:0:$(expr $slot - 1):0" >> /etc/zfs/vdev_id.conf
       		let slot=slot+1
	done
	;;
45)
	card1=$(lspci | grep $DISK_CONTROLLER | awk 'NR==1{print $1}')
	card2=$(lspci | grep $DISK_CONTROLLER | awk 'NR==2{print $1}')
	#Card 1
	slot=1
	while [ $slot -lt 25 ];do	
       		echo "alias 1-$slot     /dev/disk/by-path/pci-0000:$card1-scsi-0:0:$(expr $slot - 1):0" >> /etc/zfs/vdev_id.conf
       		let slot=slot+1
	done
	#Card 2
	slot=1
	while [ $slot -lt 22 ];do
       		if [ $slot -eq 21 ];then
       		        echo "alias 2-$slot     /dev/disk/by-path/pci-0000:$card2-scsi-0:0:23:0" >> /etc/zfs/vdev_id.conf
        	else
        	        echo "alias 2-$slot     /dev/disk/by-path/pci-0000:$card2-scsi-0:0:$(expr $slot - 1):0" >> /etc/zfs/vdev_id.conf
        	fi
        	let slot=slot+1
	done
	;;
60)
	card1=$(lspci | grep $DISK_CONTROLLER | awk 'NR==1{print $1}')
	card2=$(lspci | grep $DISK_CONTROLLER | awk 'NR==2{print $1}')
	#Card 1
	slot=1
	while [ $slot -lt 33 ];do
        	echo "alias 1-$slot     /dev/disk/by-path/pci-0000:$card1-scsi-0:0:$(expr $slot - 1):0" >> /etc/zfs/vdev_id.conf
        	let slot=slot+1
	done
	#Card 2
	slot=1
	while [ $slot -lt 29 ];do
        	echo "alias 2-$slot     /dev/disk/by-path/pci-0000:$card2-scsi-0:0:$(expr $slot - 1):0" >> /etc/zfs/vdev_id.conf
        	let slot=slot+1
	done
	;;
esac
cat /etc/zfs/vdev_id.conf
udevadm trigger
